# Generated by Django 5.2.9 on 2026-01-08 14:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Chiave sessione')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creato')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aggiornato')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Carrello',
                'verbose_name_plural': 'Carrelli',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Indirizzo')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Codice postale')),
                ('city', models.CharField(max_length=100, verbose_name='Città')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creato')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aggiornato')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagato')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('processing', 'In elaborazione'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato')], default='pending', max_length=20, verbose_name='Stato')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Immagine')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prezzo')),
                ('available', models.BooleanField(default=True, verbose_name='Disponibile')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creato')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aggiornato')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantità disponibile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Ordine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Articolo ordine',
                'verbose_name_plural': 'Articoli ordine',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantità')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Carrello')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Articolo carrello',
                'verbose_name_plural': 'Articoli carrello',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx'),
        ),
    ]
